[env:esp32-s3-lcd-314]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_8MB.csv

; Shared ESP-NOW wire protocol
lib_extra_dirs = ${PROJECT_DIR}/../../shared

lib_deps =
    bodmer/TFT_eSPI@^2.5.31
    bblanchon/ArduinoJson@^6.21.3
    lvgl/lvgl@^8.3.11
    EspDashProto

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE=1
    -I${PROJECT_DIR}/src
    -I${PROJECT_DIR}/src/ui
    -I${PROJECT_DIR}/.pio/libdeps/esp32-s3-lcd-314
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DESPDASH_NODE_WIFI=0
    -DUSER_SETUP_LOADED=1
    -DST7796_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=9
    -DTFT_DC=8
    -DTFT_RST=14
    -DTFT_BL=13
    -DTFT_BACKLIGHT_ON=HIGH
    -DTOUCH_CS=-1
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=40000000
