[env:esp32-gateway]
platform = espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    links2004/WebSockets@^2.4.1

; Wireless ArduinoOTA deployment setup
upload_protocol = espota
upload_port = esp32-gateway.local
; Fallback to USB port if OTA is not active:
; upload_port = /dev/cu.usbmodem101
