[env:esp-round-amoled-touch]
platform = espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
upload_speed = 921600

; Shared ESP-NOW wire protocol
lib_extra_dirs = ${PROJECT_DIR}/../../shared

lib_deps =
    moononournation/GFX Library for Arduino@1.4.9
    lvgl/lvgl@^8.3.11
    EspDashProto
    bblanchon/ArduinoJson@^6.21.3

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DLV_CONF_INCLUDE_SIMPLE=1
    -I${PROJECT_DIR}/src
    -I${PROJECT_DIR}/src/ui
    -I${PROJECT_DIR}/.pio/libdeps/esp-round-amoled-touch
    -DESPDASH_NODE_WIFI=0
