#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

#define LV_MEM_CUSTOM 0
// 48KB, up from node 2's 32KB (xiao-round-gauge/src/lv_conf.h:10): this
// display is TWO widget trees (panel A + panel B) on one LVGL display now,
// not one.
#define LV_MEM_SIZE (48U * 1024U)

#define LV_TICK_CUSTOM 1
#if LV_TICK_CUSTOM
    #define LV_TICK_CUSTOM_INCLUDE <Arduino.h>
    #define LV_TICK_CUSTOM_SYS_TIME_EXPR (millis())
#endif

#define LV_USE_LOG 0
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN

#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_48 1
#define LV_FONT_DEFAULT &lv_font_montserrat_14

#define LV_USE_ARC 1
#define LV_USE_LABEL 1
#define LV_USE_BAR 1
#define LV_USE_SLIDER 1
#define LV_USE_BTN 1

#ifndef LV_LABEL_LONG_undefined
#define LV_LABEL_LONG_undefined LV_LABEL_LONG_WRAP
#endif
#ifndef LV_ARC_MODE_undefined
#define LV_ARC_MODE_undefined LV_ARC_MODE_NORMAL
#endif

// NOTE: xiao-round-gauge/src/lv_conf.h additionally declares
// `extern g_telemetry_rpm/g_telemetry_throttle` plus `get_var_3500()` /
// `get_var_0()` macros here — those satisfy EEZ Studio "native variable"
// getters wired to that node's specific EEZ project (var ids 3500/0 are
// generated by THAT project, not a general LVGL thing). This node has no EEZ
// export yet (see docs/ARCHITECTURE.md S6), so there is nothing to satisfy.
// When this node's own EEZ export lands, re-add the matching
// extern/get_var_*/set_var_* block here with the var ids that export
// generates — check the exported ui.h for the exact names, they will not
// necessarily be 3500/0 again.

#endif /* LV_CONF_H */
